### ISSUE TITLE
Names are incorrect on DSC Script for Users

### ISSUE THREAD

**Issue by chboeh** [microsoft/DefendTheFlag#5]
https://github.com/microsoft/DefendTheFlag/blob/4d4238381cda3a284d0b2201670d68be96fe2c26/rs%5Cchboeh%5CDocuments%5CGitHub%5CDefendTheFlag%5CDSC%5CProvisionDcDsc.ps1#L433-L433

**Comment by chboeh** [comment]
Example:

		xADUser SamiraA
		{
			DomainName = $DomainName
			UserName = 'SamiraA'
			Password = $SamiraACreds
			Ensure = 'Present'
			GivenName = 'Samira'
			Surname = 'A'
			PasswordNeverExpires = $true
			DependsOn = @("[xADForestProperties]ForestProps", "[xWaitForADDomain]DscForestWait")
		}


Needs to be updated to:


		xADUser SamiraA
		{
			DomainName = $DomainName
			UserName = 'SamiraA'
			Password = $SamiraACreds
			Ensure = 'Present'
			GivenName = 'Samira'
			Surname = 'Abbasi'
			PasswordNeverExpires = $true
			DisplayName = 'Samira Abbasi'
			DependsOn = @("[xADForestProperties]ForestProps", "[xWaitForADDomain]DscForestWait")
		}


Submitted "pull request'

**Comment by ciberesponce** [comment]
Updated Jeff Leatherman and Samira Abbasi for appropriate Surname and Display name
